spring:
  profiles:
    active: test,dev
  jpa:
    open-in-view: false
gate:
  application: classpath:gate/application.xgapp
dssa:
  storyfile: classpath:bi-constraints.csv
#  h2:
#    console:
#      enabled: true
#      path: /console
#  datasource:
#    url: jdbc:h2:file:./data/database
#    username: sa
#    password: sa